---
title: "Reproducible Research_Course Project 1"
author: "Onno Bours"
date: "4/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data

```{r, echo = TRUE}
if(!file.exists("./data")){dir.create("./data")}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(fileUrl,destfile="./data/Dataset.zip",method="curl")

unzip(zipfile="./data/Dataset.zip",exdir="./data")
setwd("./data")

activity <- read.csv("activity.csv")
str(activity)

activity$date <- as.Date(activity$date, format = "%Y-%m-%d")
```

## What is mean total number of steps taken per day?

```{r, echo = TRUE}
library(dplyr)

total.steps.p.day <- activity %>% 
  group_by(date) %>%
  summarise(Total.Steps = sum(steps))

hist(total.steps.p.day$Total.Steps)

mean.steps.p.day <- activity %>%
  group_by(date) %>%
  summarise(Mean.Steps = mean(steps))
mean.steps.p.day

median.steps.p.day <- activity %>%
  group_by(date) %>% 
  summarise(Median.Steps = median(steps))
median.steps.p.day
```

## What is the average daily activity pattern?

```{r, echo = TRUE}
avg.steps.p.interval <- activity %>% 
  group_by(interval) %>%
  summarise(Average.Steps = mean(steps, na.rm = TRUE))

with(avg.steps.p.interval, plot(x = interval, y = Average.Steps, type = "l", ))
avg.steps.p.interval[avg.steps.p.interval$Average.Steps == max(avg.steps.p.interval$Average.Steps) ,]
```

## Imputing missing values

```{r, echo = TRUE}
summary(activity)

activityNArm <- activity
activityNArm$steps[is.na(activityNArm$steps)] <- mean(activityNArm$steps, na.rm = TRUE)

total.steps.p.dayNArm <- activityNArm %>% 
  group_by(date) %>%
  summarise(Total.Steps = sum(steps))

hist(total.steps.p.dayNArm$Total.Steps)

mean.steps.p.dayNArm <- activityNArm %>%
  group_by(date) %>%
  summarise(Mean.Steps = mean(steps))
mean.steps.p.dayNArm

median.steps.p.dayNArm <- activityNArm %>%
  group_by(date) %>% 
  summarise(Median.Steps = median(steps))
median.steps.p.dayNArm
```

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}
library(ggplot2)

# assigning the values Weekend and Weekday to the column
activityNArm$weekpart <- sapply(activity$date, function(x) {
  if(weekdays(x) == "Samstag" | weekdays(x) == "Sonntag")
  {y <- "Weekend"}
  else {y <- "Weekday"}
  y
})

# Switching from chr to factor variable
activityNArm$weekpart <- as.factor(activityNArm$weekpart)

# Creating the data set that will be plotted
activity.p.day.type <-  aggregate(steps ~ interval + weekpart, activityNArm, mean, na.rm = TRUE)

# Plotting via ggplot2
ggplot(activity.p.day.type, aes(x = interval , y = steps, color = weekpart)) + 
  geom_line() + ggtitle("Average Daily Steps by Part of the week") + 
  xlab("Interval") + 
  ylab("Average Number of Steps") +
  facet_wrap(~weekpart, ncol = 1, nrow=2) +
  scale_color_discrete(name = "Part of the week")
```













